### Sign up as a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "asdasdasd"
}

### Sign in as an existing user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "asdasdasd"
}

### who am I 
GET http://localhost:3000/auth/whoami

###
POST http://localhost:3000/auth/signout

### Get all users with Email
GET  http://localhost:3000/auth?email=asd@asd.com

### Get user by ID 
GET http://localhost:3000/auth/1
### Update user 


PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "password": "zzzzzzzz"
}

### Set a color 

GET http://localhost:3000/auth/colors/red

### Get the color 

GET http://localhost:3000/auth/colors